[server]
url = "http://127.0.0.1:30080"
cert = "tls/cert.pem"
key = "tls/key.pem"
redirect_from = [
    "http://127.0.0.1:30081",
    "https://127.0.0.1:30082",
]

[log]
actix_web = "debug"
webapp = "trace"

[postgres]
host = "127.0.0.1"
username = "sam"
password = "Captainwiz667"
database = "database"